using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace textrackMigration.Models
{
     public class AutoGeneratedParent
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
    }
    public enum Status
    {
        Completed = 0,
        InProgress = 1,
        Incomplete = 2
    }

    //This class represents the Customer 
    public class Customer : ApplicationUser
    {
        public Customer()
        {
            Orders = new HashSet<Order>();
        }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public ICollection<Order> Orders { get; set; }

    }

    //This class represents the orders made by a customer
    public class Order
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public Customer Customer { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Status Status { get; set; }
        public System.DateTime CompletedOn { get; set; }
        public System.DateTime TargetDate { get; set; }
        public string ShippingAddress { get; set; }
        public int ItemsPerBox { get; set; }
    }

    //This class represents the line orders of customers
    public class OrderLine
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public Order Order { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
    
    //This class represents the Materials available for Items
    public class Material
    {
        public Material()
        {
            Products = new HashSet<Product>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Description { get; set; }
        public ICollection<Product> Products { get; set; }

    }

    //This class represents the Colors for Items available
    public class Color
    {
        public Color()
        {
            Products = new HashSet<Product>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Name { get; set; }
        public ICollection<Product> Products { get; set; }
    }

    //This class represents the Sizes available for items available 
    public class Size
    {
        public Size()
        {
            Products = new HashSet<Product>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public ICollection<Product> Products { get; set; }
    }

    //This class represents the Products 
    public class Product : AutoGeneratedParent
    {
        public Product()
        {
            OrderLines = new HashSet<OrderLine>();
        }
        public string Description { get; set; }
        public Material Material { get; set; }
        public Color Color { get; set; }
        public Size Size { get; set; }
        public ICollection<OrderLine> OrderLines { get; set; }
    }


    //This class represents the products that will be place in a pacaking box based on 
    //Customer order
    public class Packaging
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public OrderLine OrderLine { get; set; }
        public int MaxItemsPerBox { get; set; }
        public virtual RFID RFID { get; set; }
    }


    //This class will hold the RFID information that will be used to packages
    public class RFID
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public Customer Customer { get; set; }
        public string ShippingAddress { get; set; }
        public virtual Packaging Packaging { get; set; }
    }


    //This class will store users that will be allowed to sign in to software
   
}